### ISSUE TITLE
Thanos backend

### ISSUE THREAD

**Issue by gfrntz** [provectus/swiss-army-kube#138]
Add [thanos](https://thanos.io/) backend for kube-prometheus-stack

By default, Prometheus uses an in-memory database, and restarting the pod leads to the loss of metrics. Also, the standard installation does not allow you to store metrics for longer than 14 days. You need to add a time series database for storing metrics with the ability to configure the collapse of metrics after a certain time

**Comment by akastav** [comment]
[sak-prometheus](https://github.com/provectus/sak-prometheus/pull/1)
