### ISSUE TITLE
Internal registry-proxy to avoid dockerhub limits

### ISSUE THREAD

**Issue by akastav** [provectus/swiss-army-kube#151]
**What would you like to be added**:
We need to implement "Registry as a pull-through cache" - https://docs.docker.com/registry/recipes/mirror/ and set all images to pull through this proxy

**Why is this needed**:`.
DockerHub enabled pull limits, and if we catch it and autoscaling move some system pods, pods didn't pull their image.

**Comment by viatcheslavmogilevsky** [comment]
I recently configured artifactory as registry-mirror for one of our customer - by making custom worker AMI (non eks cluster)

I'm working now how to do the same by setting user-data to ASG - for eks clusters
