### ISSUE TITLE
AWS load balancer ingress controller

### ISSUE THREAD

**Issue by random1st** [provectus/swiss-army-kube#172]
**What would you like to be added**:
https://docs.aws.amazon.com/eks/latest/userguide/aws-load-balancer-controller.html
https://github.com/helm/charts/tree/master/stable/external-dns

**Why is this needed**:`.
This feature contains an important improvement that allows using of the same ALB for few ingresses and manages Route53 with annotations

**Comment by akastav** [comment]
We have both modules with an example implementation
ALB - https://github.com/provectus/swiss-army-kube/tree/master/modules/ingress/aws-alb
External-dns - https://github.com/provectus/swiss-army-kube/tree/master/modules/system/external-dns
Also external-dns in argocd-with-applications example here https://github.com/provectus/swiss-army-kube/blob/master/examples/argocd-with-applications/main.tf#L70-L79

**Comment by random1st** [comment]
@akastav It is a deprecated AWS ALB ingress controller. I'm talking about "github.com/aws/eks-charts/stable/aws-load-balancer-controller

**Comment by akastav** [comment]
oh, sorry. We start to create a separate repository for modules and AWS ALB (with new charts) here https://github.com/provectus/sak-alb-controller/blob/main/main.tf.  
In https://github.com/provectus/swiss-army-kube/blob/master/examples/argocd-with-applications/main.tf#L143 you can see, source its remote Github repo.
We need to clean up old modules from the main repo. Thx for attention!
