### ISSUE TITLE
Create Github Actions pipeline for SAK-module repository

### ISSUE THREAD

**Issue by akastav** [provectus/swiss-army-kube#173]
**What would you like to be added**:
Github Actions Pipeline for all module repository:

Workflow:
Then PR is open:
  Need check syntax by TFLint and check style (all variables have descriptions, terraform formatting used, security check passed and sensitive data missing). Set labels and link issues if they found.
Then PR  is merged:
  Create release and set tag in the module repository with patch notes or use something like release drafter

**Why is this needed**:`.

It's a part of the full automation project workflow. Help us to check PR and update the module's version

**Comment by wallhided** [comment]
Added tflint.
Should we close this issue
