### ISSUE TITLE
sak-kubernetes doesn't work with Terraform 0.15

### ISSUE THREAD

**Issue by strawberrypie** [provectus/swiss-army-kube#174]
**Describe the bug**
Module `sak-kubernetes` produces errors like the one below when used with Terraform 0.15:
```
│ Error: Error in function call
│ 
│   on .terraform/modules/kubernetes.eks/outputs.tf line 66, in output "cloudwatch_log_group_arn":
│   66:   value       = element(concat(aws_cloudwatch_log_group.this[*].arn, list("")), 0)
│ 
│ Call to function "list" failed: the "list" function was deprecated in Terraform v0.12 and is no longer available; use tolist([ ... ]) syntax to write a literal list.
```

**Use version**
Latest version of SAK and `sak-kubernetes`, master branch.

**To Reproduce**
0. Install Terraform 0.15 (it is the latest one for Ubuntu 21.04)
1. Pull latest SAK
2. Use `sak-kubeflow` module
3. Get the error during `terraform plan`

**Expected behavior**
No errors and correctly deployed EKS cluster.

**Additional context**
[This issue](https://github.com/terraform-aws-modules/terraform-aws-eks/issues/1240) says that the problem is with outdated module version. I was able to fix this bug by updating AWS provider to `3.39.0` and `terraform-aws-modules/eks/aws` to `v15.2.0`.

**Comment by akastav** [comment]
Update sak-kubernetes module to v15.2.0 version
