### ISSUE TITLE
sak-argocd: interface is not accessible immediately after deployment

### ISSUE THREAD

**Issue by strawberrypie** [provectus/swiss-army-kube#175]
**Describe the bug**
I wasn't able to access Argo interface after the deployment on sak-argocd using the correct login / password. The problem is related to [this issue](https://github.com/argoproj/argo-cd/issues/4177#issuecomment-790872193) and removing the time parameter from Argo secret helped.

A possible fix is to set a correct time for this secret during ArgoCD deployment. (It uses local time and converts it to GMT+0 timezone by default)

**Use version**
Latest.

**To Reproduce**
1. Add ArgoCD module
2. Port-forward to ArgoCD
3. Open interface and enter login / password

**Comment by wallhided** [comment]
Trick with passwordMtime doesn't  work now. 
After some tests I noticed that newly generated password is not the same.
I'm going to remove setting of password from argocd.yaml and set it during creation of helm chart.

**Comment by wallhided** [comment]
fixed with https://github.com/provectus/sak-argocd/pull/14
