### ISSUE TITLE
Explore the possibility of upgrading to EKS 1.21 and switching to CRI instead of docker

### ISSUE THREAD

**Issue by akastav** [provectus/swiss-army-kube#185]
**What would you like to be added**:

Add support for the latest versions of EKS

**Why is this needed**:`.

Starting from the EKS 1.20 version, the transition from docker to conteinerd is underway and it will require reconfiguring some of the parameters, as well as updating all applications. It is necessary to check the possibility of switching from version 1.18 to 1.21 and a clean installation, with all the examples.

**Comment by wallhided** [comment]
https://github.com/provectus/sak-kubernetes/pull/4

**Comment by wallhided** [comment]
PR merged, Added ability to sak-kubernetes module to change CRI (docker/containerd). Left docker as default
