### ISSUE TITLE
Check status of sak-* modules.

### ISSUE THREAD

**Issue by wallhided** [provectus/swiss-army-kube#196]
Check status of all modules sak-* modules. Some of them may be broken, because of major upgrades of aws provider.

**Comment by dlazarenko76** [comment]
sak-vpc module works for me.

My environment:

`% terraform1.1 version
Terraform v1.1.8
on darwin_amd64
+ provider registry.terraform.io/hashicorp/aws v4.10.0
+ provider registry.terraform.io/hashicorp/cloudinit v2.2.0
+ provider registry.terraform.io/hashicorp/external v2.1.0
+ provider registry.terraform.io/hashicorp/helm v2.1.2
+ provider registry.terraform.io/hashicorp/kubernetes v2.2.0
+ provider registry.terraform.io/hashicorp/local v2.1.0
+ provider registry.terraform.io/hashicorp/null v3.1.0
+ provider registry.terraform.io/hashicorp/random v3.1.0
+ provider registry.terraform.io/hashicorp/template v2.2.0
+ provider registry.terraform.io/terraform-aws-modules/http v2.4.1`

**Comment by dlazarenko76** [comment]
All other modules seem to work as expected
