### ISSUE TITLE
Add StorageClass, PV and PVC for EFS

### ISSUE THREAD

**Issue by strawberrypie** [provectus/swiss-army-kube#65]
Currently, StorageClass, PersistentVolume and PersistentVolumeClaim need to be manually added via `kubectl apply` after the deployment. `volumeHandle` for the PV needs to be set manually.
We need to automate their creation.

**Comment by wallhided** [comment]
https://github.com/provectus/sak-incubator/pull/10

**Comment by wallhided** [comment]
Also I need to remove creating of PV and add dynamic-provisioning

**Comment by wallhided** [comment]
https://github.com/provectus/sak-incubator/pull/13/files

**Comment by wallhided** [comment]
Added to incubator (storage/efs)
