### ISSUE TITLE
Remove minio from argo-workflow

### ISSUE THREAD

**Issue by strawberrypie** [provectus/swiss-army-kube#67]
During the deployment of a new Kubeflow cluster I've encountered an error: 
> `SetUp failed for volume "argo-workflow-minio" : secret "argo-workflow-minio" not found`

This `argo-workflow-minio` was specified in the ConfigMap for `argo-workflow-workflow-controller-configmap` and removing it removed the error. It seems that minio as an artifact storage wasn't removed after all.

**Comment by akastav** [comment]
https://github.com/provectus/sak-kubernetes
